name: pulling from 3rd party

env:
  GIT_REPO: https://gitlab.com/linjrp/ping.git
  GIT_PRIVATE: ${{ secrets.GIT_PRIVATE_REPO }}

on:
  push:
    branches:
    - pull3

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: CLONE FROM PUBLIC
        run: |
          git version
          git clone ${{ env.GIT_REPO }}
          cat ping/text

      - name: CLONE FROM PRIVATE
        run: |
          git version
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GIT_PRIVATE_REPO }} mydir
          cat mydir/*.md

