name: pulling from 3rd party

env:
  GIT_REPO: https://gitlab.com/linjrp/ping.git

on:
  push:
    branches:
    - pull3

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        run: |
          git version
          git clone https://gitlab.com/linjrp/ping.git
          cat ping/text