name: pulling from 3rd party

env:
  GIT_REPO: https://gitlab.com/linjrp/ping.git
  GIT_PRIVATE: https://gitlab.com/linjrp/ping-private.git

on:
  push:
    branches:
    - pull3

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: CLONE FROM PUBLIC
        run: |
          git version
          git clone ${{ env.GIT_REPO }}
          cat ping/text

      - name: CLONE FROM PRIVATE
        run: |
          git version
          git clone linjrp:${{ secrets.GITLAB_TOKEN }}@${{ env.GIT_PRIVATE }}
          cat ping-private/flag

